server:
  port: 9296

spring:
  application:
    name: CONFIG-SERVER
  cloud:
    config:
      server:
        git:
          uri: https://github.com/parithoshpoojary/ms-config-server
          default-label: main
          clone-on-start: true

eureka:
  instance:
    preferIpAddress: true
    hostname: eureka-0
  client:
    register-with-eureka: false
    fetch-registry: false
    serviceurl:
      defaultZone: http://eureka-0.eureka.default.svc.cluster.local:8761/eureka